### ISSUE TITLE
'MazeEnvRandom10x10Plus' object has no attribute 'monitor'

### ISSUE THREAD

**Issue by arashmahyari** [tuzzer/ai-gym#9]
I try to run the sample code you have, it gives me this error. Gym is installed and working.

```
Traceback (most recent call last):

  File "./q_learning_maze.py", line 192, in <module>
    env.monitor.start(recording_folder, force=True)

  File "/home/user/anaconda3/lib/python3.7/site-packages/gym/core.py", line 216, in __getattr__
    return getattr(self.env, name)

AttributeError: 'MazeEnvRandom10x10Plus' object has no attribute 'monitor'
```

**Comment by christiangfv** [comment]
I have the same problem. Do you know what is the solution?

**Comment by chirag4798** [comment]
set ENABLE_RECORDING=False in the script, by default its set to True and is used for recording the episodes in videos. The script will run fine after that, but will not record anything.
